<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tickets;

class TicketSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {        Tickets::insert([
        [
            'user_id' => 1,
            'image' => 'ticket2.png',
            'number_day_of_week' => '1',
            'month'=>'1',
            'name'=>'Vé tháng hăng say',
            'code_ticket'=>'TICKET123',
            'price'=>'1000000',
            'timeout'=>'2022-07-16',
            'discount'=>10,
            'ispay' =>'0',
        ],
        [
            'user_id' => 2,
            'image' => 'ticket1.png',
            'number_day_of_week' => '2',
            'month'=>'1',
            'name'=>'Vé tháng chăm chỉ',
            'code_ticket'=>'TICKET123',
            'price'=>'2000000',
            'timeout'=>'2022-07-16',
            'discount'=>0,
            'ispay' =>'0',
        ],
        [
            'user_id' => 3,
            'image' => 'abrf.png',
            'number_day_of_week' => '1',
            'month'=>'1',
            'name'=>'Vé tháng hăng say',
            'code_ticket'=>'TICKET123',
            'price'=>'1000000',
            'timeout'=>'2022-07-16',
            'discount'=>10,
            'ispay' =>'0',
        ],
        [
            'user_id' => 4,
            'image' => 'ticket1.png',
            'number_day_of_week' => '2',
            'month'=>'1',
            'name'=>'Vé tháng chăm chỉ',
            'code_ticket'=>'TICKET123',
            'price'=>'2000000',
            'timeout'=>'2022-07-19',
            'discount'=>10,
            'ispay' =>'0',
        ],
        [
            'user_id' => 5,
            'image' => 'ticket1.png',
            'number_day_of_week' => '1',
            'month'=>'1',
            'name'=>'Vé tháng hăng say',
            'code_ticket'=>'TICKET123',
            'price'=>'1000000',
            'timeout'=>'2022-07-17',
            'discount'=>0,
            'ispay' =>'0',
        ],
        [
            'user_id' => 6,
            'image' => 'ticket1.png',
            'number_day_of_week' => '2',
            'month'=>'1',
            'name'=>'Vé tháng chăm chỉ',
            'code_ticket'=>'TICKET123',
            'price'=>'2000000',
            'timeout'=>'2022-07-18',
            'discount'=>0,
            'ispay' =>'0',
        ],
        [
            'user_id' => 7,
            'image' => 'ticket1.png',
            'number_day_of_week' => '1',
            'month'=>'1',
            'name'=>'Vé tháng hăng say',
            'code_ticket'=>'TICKET123',
            'price'=>'1000000',
            'timeout'=>'2022-07-17',
            'discount'=>0,
            'ispay' =>'0',
        ],
        [
            'user_id' => 8,
            'image' => 'ticket1.png',
            'number_day_of_week' => '2',
            'month'=>'1',
            'name'=>'Vé tháng chăm chỉ',
            'code_ticket'=>'TICKET123',
            'price'=>'2000000',
            'timeout'=>'2022-07-20',
            'discount'=>20,
            'ispay' =>'0',
        ],
        [
            'user_id' => 9,
            'image' => 'ticket1.png',
            'number_day_of_week' => '1',
            'month'=>'1',
            'name'=>'Vé tháng hăng say',
            'code_ticket'=>'TICKET123',
            'price'=>'1000000',
            'timeout'=>'2022-07-21',
            'discount'=>10,
            'ispay' =>'0',
        ],
        [
            'user_id' => 10,
            'image' => 'ticket1.png',
            'number_day_of_week' => '2',
            'month'=>'1',
            'name'=>'Vé tháng chăm chỉ',
            'code_ticket'=>'TICKET123',
            'price'=>'2000000',
            'timeout'=>'2022-07-19',
            'discount'=>0,
            'ispay' =>'0',
        ],
        [
            'user_id' => 11,
            'image' => 'ticket1.png',
            'number_day_of_week' => '1',
            'month'=>'1',
            'name'=>'Vé tháng hăng say',
            'code_ticket'=>'TICKET123',
            'price'=>'1000000',
            'timeout'=>'2022-07-18',
            'discount'=>10,
            'ispay' =>'0',
        ],
        [
            'user_id' => 12,
            'image' => 'ticket1.png',
            'number_day_of_week' => '2',
            'month'=>'1',
            'name'=>'Vé tháng chăm chỉ',
            'code_ticket'=>'TICKET123',
            'price'=>'2000000',
            'timeout'=>'2022-07-17',
            'discount'=>20,
            'ispay' =>'0',
        ],
    ]);
    }
}
